title: Thomas Barlow
logo: "/images/headshot.png?raw=true"
description: > 
  Hello, I'm currently a Full Stack Software Engineer at iTSpeeX LLC. In my free time I like 3D printing, and working on software projects. Check out some of the projects I've worked on!
  <br>
  Currently looking for new employment! Reach out to me below or on LinkedIn if you're interested in having me on your team.
  <br><br>
  <a href ="mailto: contact@thomasjbarlow.com">Contact Me</a>
  <br><br>
  <a href="https://www.linkedin.com/in/thomas-barlow/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://thomasjbarlow.com/work_experience">Work Experience</a> 
  <br>
  <a href="https://thomasjbarlow.com/flip_clock">Smart Flip Clock</a> 
  <br>
  <a href="https://thomasjbarlow.com/shift_knob">Custom Shift Knob</a> 
  <br>
  <a href="https://thomasjbarlow.com/model_design">Other 3D Prints</a> 
  <br>
  <a href="https://thomasjbarlow.com/skribblio_bot">Skribblio Drawing Bot</a> 
  <br>
  <a href="https://thomasjbarlow.com/wordkeeper">Discord Wordkeeper Bot</a> 
  <br>
  


  
theme: jekyll-theme-minimal
google_analytics: UA-141278946-1 # your Google Analytics tracking ID here
